defaults:
  - default

strategy: ddp # _find_unused_parameters_true # ddp

accelerator: gpu
devices: 1
num_nodes: 1
sync_batchnorm: true
max_epochs: 100
check_val_every_n_epoch: 2
gradient_clip_val: 0.5
accumulate_grad_batches: 1
precision: 32-true
log_every_n_steps: 50