# @package _global_
defaults:
  - override /data: rlbench_diffusion_policy_rgbd_dataset
  - override /model: rlbench_diffusion_policy_model

task_name: pretrained_r3m_rgb

model:
  policy:
    shape_meta:
      obs:
        front_rgb:
          shape: [3, 128, 128]
          type: rgb
        qpos:
          shape:
            - ${data.train.action_dim}
          type: low_dim
    obs_encoder:
      rgb_model:
        _target_: src.models.components.img_encoder.resnet.R3MResNet
        resnet_model: resnet50
        channels: 3
        avg_pool: true