# @package _global_
defaults:
  - override /data: rlbench_diffusion_policy_pcd_dataset
  - override /model: rlbench_diffusion_policy_model

task_name: scratch_pointnet_pcd

data:
  batch_size_train: 16

trainer:
  accumulate_grad_batches: 2
  
model:
  policy:
    shape_meta:
      obs:
        pcds:
          shape: [6]
          type: pcd
        qpos:
          shape:
            - ${data.train.action_dim}
          type: low_dim
    obs_encoder:
      _target_: src.models.components.diffusion_policy.vision.pcd_obs_encoder.PCDObsEncoder
      shape_meta: ${model.policy.shape_meta}
      pcd_model:
        _target_: src.models.components.pcd_encoder.pointnet.PointNet
        in_channels: 6
        num_classes: 96
        pretrained_path: null 
      share_pcd_model: true
      n_obs_step: ${model.policy.n_obs_steps}
      pcd_nsample: 16
      pcd_npoints: 2048
      use_mask: false
      bg_ratio: 0.0
      pcd_hidden_dim: 96
      projector_layers: 1
      projector_channels: [96, 128, 128]