# @package _global_
defaults:
  - override /data: rlbench_diffusion_policy_rgbd_dataset
  - override /model: rlbench_diffusion_policy_model

task_name: scratch_resnet50_rgbd

data:
  train:
    include_depth: true

model:
  policy:
    shape_meta:
      obs:
        front_rgb:
          shape: [3, 128, 128]
          type: rgb
        front_depth:
          shape: [1, 128, 128]
          type: depth
        qpos:
          shape:
            - ${data.train.action_dim}
          type: low_dim
    obs_encoder:
      rgb_model:
        _target_: src.models.components.img_encoder.resnet.ResNetTorchVision
        resnet_model: resnet50
        pretrained: false
        channels: 4
        avg_pool: true
      use_depth: true