# @package _global_
defaults:
  - override /data: rlbench_act_pcd_dataset
  - override /model: rlbench_act_pcd_model

task_name: pretrained_ponderv2_pcd

data:
  batch_size_train: 16

trainer:
  accumulate_grad_batches: 2
  
model:
  policy:
    backbone:
      _target_: src.models.components.pcd_encoder.spunet.SpUNet
      in_channels: 6
      num_classes: 0
      pretrained_path: checkpoints/ponderv2-ppt-pretrain-scannet-s3dis-structured3d.pth