# @package _global_
defaults:
  - override /data: rlbench_act_rgbd_dataset
  - override /model: rlbench_act_model

task_name: pretrained_multimae_rgbd

data:
  batch_size_train: 16
  train:
    include_depth: true

trainer:
  accumulate_grad_batches: 2

model:
  policy:
    backbone: 
      _target_: src.models.components.img_encoder.multivit.MultiMAEModel
