# @package _global_
defaults:
  - override /data: rlbench_act_rgbd_dataset
  - override /model: rlbench_act_model

task_name: pretrained_vc1_rgb

model:
  policy:
    backbone:
      _target_: src.models.components.img_encoder.vit.VC1ViT
      model_name: vit_base_patch16
      channels: 3