# @package _global_
defaults:
  - override /model: maniskill2_diffusion_policy_model
  - override /paths: default

task_name: pretrained_r3m_rgb

model:
  policy:
    shape_meta:
      obs:
        base_camera_rgb:
          shape: [3, 128, 128]
          type: rgb
        qpos:
          shape: [7]
          type: low_dim
    obs_encoder:
      rgb_model:
        _target_: src.models.components.img_encoder.resnet.R3MResNet
        resnet_model: resnet50
        channels: 3
        avg_pool: true
