# @package _global_
defaults:
  - override /model: maniskill2_diffusion_policy_model
  - override /paths: default

task_name: scratch_resnet50_pointmap

data:
  train:
    pointmap: true

model:
  obs_mode: pointcloud
  policy:
    shape_meta:
      obs:
        base_camera_rgb:
          shape: [6, 128, 128]
          type: rgb
        qpos:
          shape: [7]
          type: low_dim
    obs_encoder:
      rgb_model:
        _target_: src.models.components.img_encoder.resnet.ResNetTorchVision
        resnet_model: resnet50
        pretrained: false
        channels: 6
        avg_pool: true