# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}/tensorboard/"
  name:
  log_graph: false
  default_hp_metric: true
  prefix: ""
  version: ${task_name}
