defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - lr_monitor
  - device_stats_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: true
  auto_insert_metric_name: false
  save_top_k: 3

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
